safe: true
markdown: kramdown
highlighter: pygments
permalink: /:title.html
relative_permalinks: false

default_theme: bright
default_width: 792
default_lang: en
default_body_class: full

author:
    name: Igor Strebezhev
    url:  http://github.com/xamgore
    # company:
        # name: Famous Inc.
        # url:  http://example.com/

fork_url: https://github.com/shower/shower
progress: true
line_numbers: false
